### ISSUE TITLE
Does it support refresh token ?

### ISSUE THREAD

**Issue by arminioa** [fydrah/loginapp#11]
Hi,

I can't figure out how to configure loginapp to return a refresh token.
Does it support it?

Thanks

**Comment by fydrah** [comment]
Which version of loginapp do you use and what is the configuration ?

**Comment by fydrah** [comment]
Do you use *oidc.offline_as_scope* option ?

**Comment by arminioa** [comment]
Hey @fydrah,
Sorry for my late response.
It seems that I missed this option _ offline_as_scope: true_ as you said.

Thank you for your support.

**Comment by fydrah** [comment]
You're welcome ;)
