### ISSUE TITLE
dns lookup broken

### ISSUE THREAD

**Issue by jpecar** [fydrah/loginapp#13]
I'm getting "dial tcp: lookup dex.example.com on 169.254.25.10:53: no such host" where example.com is actually a real domain, but I have no idea where 169.254.25.10 is coming from. There's no dns on that IP that would be able to answer and as a result loginapp does not start up.

Googling around tells me this is somehow related to docker enigne config but I find this unlikely since this particular container is the only one that is having this issue.

I tried rebuilding it with added /etc/resolv.conf but it is completely ignored (or somehow overwritten).

Next I'll dig into the go source ... 

Any hints appreciated.

**Comment by fydrah** [comment]
Hi @jpecar ,

First question: how do you deploy loginapp ? On kubernetes ? On a single docker host ? Without docker, just using the binary ?

You can find an example of local deployment (for testing purposes) [here (with docker-compose)](https://github.com/fydrah/loginapp/blob/master/docker-compose.yml). In this file, I use a [static host entry](https://github.com/fydrah/loginapp/blob/master/docker-compose.yml#L20), where dex.example.org is resolved as localhost (again, for testing purposes only).

If you use the loginapp binary, you just have to put `127.0.0.1 dex.example.org` into your `/etc/hosts`.

Hope it helps.
Regards,

**Comment by jpecar** [comment]
We deploy to kubernetes environment set up by kubespray.

Is /etc/hosts file the only way this app knows how to resolve names?

**Comment by fydrah** [comment]
> Is /etc/hosts file the only way this app knows how to resolve names?
No, loginapp will use your resolvconf, hosts file is just used for testing :)
In a Kubernetes environment, loginapp will be able to resolve services like any other app.

> Is there anything I can do to make it accept invalid cert?
Currently, no. You can quickly generate testing certs with [this script](https://github.com/dexidp/dex/blob/master/examples/k8s/gencert.sh)

**Comment by jpecar** [comment]
I did try to add /etc/resolv.conf into the container, without change in behavior. It's still trying to query nonexistant dns on a link-local ipv4 address. I guess this must either be some quirk of muse-libc used by alpine or something I don't know yet about kubernetes-docker interaction.

Anyway, hosts entry works for now and is good enough for testing.

Should we continue discussing cert isuse in this thread or should I open another issue? Because browsers show the cert as valid and loginapp is rejecting it. Looks like I need to learn how the go world is dealing with certificates and trusted CAs.

**Comment by jpecar** [comment]
Ok, I sorted out the certs ... next issue looks like dex related:
https://dex.example.local/dex/.well-known/openid-configuration gives me the expected json, but
https://dex.example.local/dex/ is 404 which loginapp doesn't like.
What should be there and why is it not there?

**Comment by fydrah** [comment]
Hi @jpecar ,

Could you paste your loginapp & dex configuration (without secrets) ?
Also, could you show me how you deploy loginapp on kubernetes ?
It is harder to help you without more visibility.

**Comment by jpecar** [comment]
Ok, after some studying of what talks to what and how, I got this to work.

My next two challenges:
"Copy this into your .kube/config file" text returned is not suitable for a brainless copy/paste. There needs to be at least a cluster, context and current-context definition. Only then can the presented text chunk be appended to .kube/config. Can this be documented with some examples somewhere?

Some documentation and examples on how to design some RBAC rules for the "logged-in" users would be nice as well.
