### ISSUE TITLE
Return support for mounted template and assets

### ISSUE THREAD

**Issue by rinrailin** [fydrah/loginapp#26]
**Is your feature request related to a problem? Please describe.**
It was very convenient to have the possibility to override default template and assets with volume mounts. Such possibility was removed in 3.0.0 release.

**Describe the solution you'd like**
It will be a good idea to check if template file and/or assets directory exists. If they exists -- use template/assets from file system. If not -- use default template/assets, bundled with packr/v2

**Describe alternatives you've considered**
The only alternative for now is building own loginapp image, which is not a good solution.

**Additional context**
none

**Comment by fydrah** [comment]
hi, yes feature was dropped, my bad.
Thank you for the PR !
I'm currently looking at it.

**Comment by fydrah** [comment]
PR #27 merged. Closing issue

Thanks !

**Comment by fydrah** [comment]
@rinrailin v3.1.0 has just been released, it contains PR #27 and a security fix

helm chart v1.0.2 (for app v3.1.0) also released
