### ISSUE TITLE
Support using a specific LoadBalancer IP

### ISSUE THREAD

**Issue by bsnape** [fydrah/loginapp#29]
**Is your feature request related to a problem? Please describe.**
It is sometimes necessary to require a specific IP for Kubernetes services (e.g. for DNS).

**Describe the solution you'd like**
Fixed in #28 

**Additional context**
Tested internally and working across multiple clusters.

**Comment by fydrah** [comment]
#28 merged, helm chart v1.0.3 deployed on repository.

Thanks!
