### ISSUE TITLE
CrashLoopBackOff error

### ISSUE THREAD

**Issue by lich12345** [fydrah/loginapp#3]
NAMESPACE NAME READY STATUS RESTARTS AGE
auth dex-d7f5666ff-5r7z4 1/1 Running 0 14m
auth loginapp-5fdc77b6b5-mwx2s 0/1 CrashLoopBackOff 4 2m

dex-cm.yml
...
oauth2:
skipApprovalScreen: true

staticClients:
- id: loginapp
  redirectURIs:
  - 'https://139.126.118.237:32002/callback'
  name: 'Loginapp'
  secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
- id: web
  redirectURIs:
  - 'https://139.126.118.237:32002/callback'
  name: 'Web'
  secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
  trustedPeers:
  - loginapp
loginapp-cm.yml
apiVersion: v1
metadata:
name: loginapp
namespace: auth
data:
config.yaml: |
name: "Kubernetes Auth"
listen: "0.0.0.0:5555"
oidc:
client:
id: "loginapp"
secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
redirect_url: "https://139.126.118.237:32002/callback"
issuer:
root_ca: "/etc/kubernetes/ssl/ca_jvl.pem"
url: "https://139.126.118.237:32000/dex"
extra_scopes:
- groups
offline_as_scope: true
cross_clients:
- web
tls:
enabled: true
cert: "/etc/loginapp/tls/tls.crt"
key: "/etc/loginapp/tls/tls.key"
log:
level: debug
format: json
web_output:
main_client_id: loginapp
skip_main_page: true

loginapp-deploy.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: loginapp
namespace: auth
spec:
replicas: 1
template:
metadata:
labels:
app: loginapp
spec:
containers:
- image: quay.io/fydrah/loginapp:latest
name: loginapp
ports:
- name: http
containerPort: 5555
volumeMounts:
- name: ca
mountPath: /etc/kubernetes/ssl/
- name: config
mountPath: /app/
- name: tls
mountPath: /etc/loginapp/tls
volumes:
- name: ca
configMap:
name: ca
items:
- key: ca_jvl.pem
path: ca_jvl.pem
- name: config
configMap:
name: loginapp
items:
- key: config.yaml
path: config.yaml
- name: tls
secret:
secretName: loginapp.local.tls

auth loginapp-5fdc77b6b5-wsptn 0/1 CrashLoopBackOff 2 1m

logs loginapp-5fdc77b6b5-wsptn -n auth -f
NAME:
loginapp - A new cli application

USAGE:
Web application for Kubernetes CLI configuration with OIDC

COMMANDS:
serve Run loginapp application
help, h Shows a list of commands or help for one command

OPTIONS:
--help, -h show help
--version, -v print the version

Thanks for the help in advance!

**Comment by fydrah** [comment]
Hi,

Could you print the output of:
```
kubectl describe pod <loginapp_pod>
```
It seems the entrypoint/cmd is not correct, it should start the container with:
```
/loginapp serve /config.yaml
```

**Comment by fydrah** [comment]
Hi @lich12345, any news about this issue ?

**Comment by lich12345** [comment]
Had to rebuild it:

Here is kubectl describe:
`kubectl describe deployment loginapp -n auth
Name:                   loginapp
Namespace:              auth
CreationTimestamp:      Mon, 15 Oct 2018 13:28:08 -0600
Labels:                 app=loginapp
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=loginapp
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=loginapp
  Containers:
   loginapp:
    Image:        quay.io/fydrah/loginapp:latest
    Port:         5555/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /app/ from config (rw)
      /etc/kubernetes/ssl/ from ca (rw)
      /etc/loginapp/tls from tls (rw)
  Volumes:
   ca:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ca
    Optional:  false
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      loginapp
    Optional:  false
   tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  loginapp.local.tls
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  loginapp-5fdc77b6b5 (1/1 replicas created)
NewReplicaSet:   <none>
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  4m12s  deployment-controller  Scaled up replica set loginapp-5fdc77b6b5 to 1
`
Using: Docker Image: Image: quay.io/fydrah/loginapp:latest

**Comment by fydrah** [comment]
Okay, like I said a cmd/entrypoint is missing in the deployment.
As you can see, in the [Dockerfile](https://github.com/fydrah/loginapp/blob/master/Dockerfile#L16) we only specify `/loginapp` for entrypoint.

You have to update loginapp deployment manifest, and add these lines to the pod description:
```
args: ["server", "/app/config.yaml"]
```
This should work.

You can also completely override the default entrypoint:
```
command: ["/loginapp"]
args: ["server", "/app/config.yaml"]
```

A suggestion, avoid to use the "latest" tag from loginapp image. This tag refers to the master branch, but if we change the behavior of loginapp (like I did a couple of month ago with the CLI), it will break your deployment.
Instead, use a [tagged release](https://quay.io/repository/fydrah/loginapp?tab=tags) (ex: `2.2.0`)

Hope I helped

**Comment by fydrah** [comment]
Hi @lich12345, do you still have issues during loginapp startup ?

**Comment by lich12345** [comment]
N,o everything is good thanks for the help!

**Comment by fydrah** [comment]
Okay ! Thanks for the feedback, I close this issue.
