### ISSUE TITLE
Web.Kubeconfig.ExtraOpts expected a map, got 'string'

### ISSUE THREAD

**Issue by r0bj** [fydrah/loginapp#37]
**Describe the bug**
Config without explicitly defined `Web.Kubeconfig.ExtraOpts`:
```
oidc:
  web:
    kubeconfig:
      extraOpts: {}
```

Causing fatal error:
```
{"level":"fatal","msg":"1 error(s) decoding:\n\n* 'Web.Kubeconfig.ExtraOpts' expected a map, got 'string'","time":"2020-11-30T19:02:32Z"}
```

**Loginapp & Dex version**
loginapp: `v3.2.0`

**Expected behavior**
Config without explicitly defined `Web.Kubeconfig.ExtraOpts` use proper default which allow loginapp to run.

**Comment by fydrah** [comment]
My bad...I made a mistake during config setup... Pushing update soon

**Comment by r0bj** [comment]
@fydrah any reason there is no `quay.io/fydrah/loginapp:v3.2.1` available yet?

**Comment by fydrah** [comment]
yep quay.io build stuck since yesterday... I triggered it again

**Comment by fydrah** [comment]
cause: docker hub rate limiting...

**Comment by fydrah** [comment]
I cannot rebuild image now, because of this fantastic rate limit. You still can use master image, it is the same code as v3.2.1

**Comment by fydrah** [comment]
I pushed local build to v3.2.1, so you can use it now if you want

**Comment by r0bj** [comment]
Thanks!
