### ISSUE TITLE
Web interface looks different than in demo screen shot?

### ISSUE THREAD

**Issue by sense-amid-madness** [fydrah/loginapp#40]
**Describe the bug**

I have setup the full login framework with dex now and it seems to work. However, after login to our cluster, the screen I see looks different than the one in your demo screen shot: There is no menu on the left hand side, and there is no full kubeconfig for users (just a box with the user credentials and one other with a kubectl command line).

When was the interface changed? v3.2.0 can not parse my config so I am stuck with v2.5.0, so I guess it's due to the old version?

Thanks.

**Loginapp & Dex version**
loginapp: `v2.5.0`
dex: `v2.27.0`

**Comment by fydrah** [comment]
Hi @sense-amid-madness ,

Yes UI has changed. Like I said in #39 a fix is available in `v3.2.1`.

New UI features are available since https://github.com/fydrah/loginapp/releases/tag/2.7.0

**Comment by sense-amid-madness** [comment]
Ok, fix works. Thanks.
