### ISSUE TITLE
loginapp_request_duration constantly increases 

### ISSUE THREAD

**Issue by rpig2021** [fydrah/loginapp#43]
**Describe the bug**
loginapp_request_duration metrics constantly increase. I have loginapp/dex deployed on multiple clusters and want to setup an alert based on the loginapp_request_duration metric. Based on that: https://github.com/fydrah/loginapp/blob/master/pkg/server/prometheus.go#L42 I would expect that metric is more fluctuating when in my case(6 different deployment) it just increases. 

Do I misunderstand anything there? 

**Loginapp & Dex version**
loginapp: `v3.0.1` helm chart: loginapp-v1.0.1
dex: `v2.24.0`

**Configuration**
I think not relevant but happy to provide but not sure what. 

**To Reproduce**
1. Go to Prometheus
2. Search for loginapp_request_duration {code=200} [1w]
4. See in output as a raising seconds 

**Expected behavior**
I would expect loginapp_request_duration is more fluctuant 

**Screenshots**

<img width="1438" alt="Screenshot 2021-03-12 at 12 24 23" src="https://user-images.githubusercontent.com/80517863/110934554-6f103700-832e-11eb-89fc-8649ccb44b5d.png">
<img width="1409" alt="Screenshot 2021-03-12 at 12 23 55" src="https://user-images.githubusercontent.com/80517863/110934608-80f1da00-832e-11eb-9e26-338157688e54.png">

**Comment by rpig2021** [comment]
I review the logs and I see request_duration time but not sure if that should match the metrics:
`kubectl logs -n kube-system loginapp-c954f8d5-8dnb6 |grep '"code":50'
{"code":500,"level":"info","method":"GET","msg":"","path":"/callback?code=hk3venoebwgeppq42qjmegnr5\u0026state=gOpbh2WvVGzfx3TaSxsleqMPUBmuAqm8Mt4sQ4507Dk%3D","protocol":"HTTP/2.0","remote_address":"192.168.74.0:57398","request_duration":"7.932974ms","time":"2021-02-11T08:54:26Z"}
{"code":500,"level":"info","method":"GET","msg":"","path":"/callback?code=ebe5py5fitomigkgxdgwpg24p\u0026state=nEpFUQsk89y4aeunqh5QgTl1gOqmhk109%2Bccc%2FL6xOQ%3D","protocol":"HTTP/1.1","remote_address":"192.168.143.64:2090","request_duration":"4.827864ms","time":"2021-02-11T15:33:53Z"}`

or 200
`kubectl logs -n kube-system loginapp-c954f8d5-8dnb6 |grep '"code":200' |head -n 10
{"code":200,"level":"info","method":"GET","msg":"","path":"/healthz","protocol":"HTTP/2.0","remote_address":"172.24.201.93:36094","request_duration":"796.03µs","time":"2021-02-10T17:27:06Z"}
{"code":200,"level":"info","method":"GET","msg":"","path":"/healthz","protocol":"HTTP/2.0","remote_address":"172.24.201.93:36114","request_duration":"925.778µs","time":"2021-02-10T17:27:11Z"}
{"code":200,"level":"info","method":"GET","msg":"","path":"/healthz","protocol":"HTTP/2.0","remote_address":"172.24.201.93:36130","request_duration":"1.140415ms","time":"2021-02-10T17:27:16Z"}
{"code":200,"level":"info","method":"GET","msg":"","path":"/healthz","protocol":"HTTP/2.0","remote_address":"172.24.201.93:36144","request_duration":"956.477µs","time":"2021-02-10T17:27:21Z"}
{"code":200,"level":"info","method":"GET","msg":"","path":"/healthz","protocol":"HTTP/2.0","remote_address":"172.24.201.93:36156","request_duration":"769.293µs","time":"2021-02-10T17:27:26Z"} `

**Comment by fydrah** [comment]
Hello @rpig2021 ,

Indeed, it seems I use `func (g *Gauge) Add(delta float64)` instead of func (g *Gauge) Set(value float64) for this gauge vector metric....bad mistake, I'll test and push the update soon

**Comment by fydrah** [comment]
fixed in v3.2.3 (helm v1.0.7)

**Comment by fydrah** [comment]
Re-open this issue and let me know if the fix does not solve your problem (it should!)

**Comment by rpig2021** [comment]
It works perfectly fine after the upgrade. Thanks for so quick fixup. [
<img width="1431" alt="Screenshot 2021-03-16 at 12 07 34" src="https://user-images.githubusercontent.com/80517863/111299670-82821180-8650-11eb-9cf9-f0897e0d2f6c.png">
](url)
