### ISSUE TITLE
Helm charts-  provide custom templates for error and token pages

### ISSUE THREAD

**Issue by Imunhatep** [fydrah/loginapp#45]
**Is your feature request related to a problem? Please describe.**
Unable to provide/override custom html templates for loginapp

**Describe the solution you'd like**
Add configmap with `error.html` and `token.html` keys that will be mounted as a volume at `/web/templates/` overriding default templates.

**Describe alternatives you've considered**
Not much alternatives as this requires changes in deployment manifest

**Additional context**
Would be nice to be able to provide custom values that would be passed as is to a html templates (e.g. provide values in loginapp configuration)

**Comment by fydrah** [comment]
Hello @Imunhatep , indeed this could be nice to include this override, since we can override with the standalone cli, the helm chart should allow it also.
I'm going to look at the PR asap

**Comment by fydrah** [comment]
Available in helm chart v1.1.0
