### ISSUE TITLE
helm repository is unreachable

### ISSUE THREAD

**Issue by boufleur** [fydrah/loginapp#48]
**Describe the bug**
I'm trying to install loginapp via the helm chart, but I'm getting a 403 error from registry.fhardy.fr

**Loginapp & Dex version**
loginapp: `v1.1.0`
dex: `v0.3.3`

**To Reproduce**
1. execute `helm repo add fhardy-stable https://registry.fhardy.fr/chartrepo/stable`

**Expected behavior**
Repository is added to helm

**Comment by fydrah** [comment]
Hi,

yes I had some infra issues (I'm currently migrating a lot of things..). The repository is now available.

I will change the repository DNS soon for https://charts.fydrah.com/, I'll update the chart README then.

Thanks for the warning :)

**Comment by boufleur** [comment]
Yes, I see it working now. Thanks.

**Comment by sennerholm** [comment]
The old url is not working and it's still pointing to that in the README

**Comment by fydrah** [comment]
This has been updated
