### ISSUE TITLE
update helm template ingress apiVersion to compatible with k8s 1.19+

### ISSUE THREAD

**Issue by fsdrw08** [fydrah/loginapp#55]
**Describe the bug**
Error pops up when install loginapp via helm install which set ingress enabled to true in k3s version v1.22.5+k3s1

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1b

**Loginapp & Dex version**
loginapp: `vX.X.X`
dex: `vX.X.X`

**Configuration**
see https://github.com/fsdrw08/SoloLab/blob/main/HelmWorkShop/loginapp/values.yaml

Current loginapp (and eventually dex) configuration (*without secrets*)
```
...
ingress:
  enabled: true
...
```

**To Reproduce**
```
helm install loginapp fydrah-stable/loginapp \
    --namespace dex \
    --values $(wget -q -O /dev/stdout https://raw.githubusercontent.com/fsdrw08/SoloLab/main/HelmWorkShop/loginapp/values.yaml)
```

**Expected behavior**
should install loginapp with ingress as expect

**Additional context**
refere https://github.com/dexidp/helm-charts/blob/master/charts/dex/templates/ingress.yaml#L9 ,  
should update helm chart ingress.yaml (insert below code in line 4 in https://github.com/fydrah/loginapp/blob/master/helm/loginapp/templates/ingress.yaml)
```
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
```

**Comment by fydrah** [comment]
Hi @fsdrw08 ,

Thanks for reporting the issue. You can try with chart v1.3.1, it supports kube v1.19+ ingresses api version (networking/v1).

**Comment by fsdrw08** [comment]
it works now, thanks
