### ISSUE TITLE
Customize "Copy this in your ~/.kube/config file" page

### ISSUE THREAD

**Issue by emptywee** [fydrah/loginapp#6]
Hi and thanks for the great login app.

Is there any plans to allow customization of the "Copy this in your ~/.kube/config file" page? I'd like to make it a bit more clear where to place it exactly. And maybe provide per-cluster instructions.

Just curious at this time.

**Comment by fydrah** [comment]
Hi @emptywee ,

This was not planed, but it is a good idea.

I could extract the HTML templates from the code, then you will be able to configure whatever you want in the template (no need to re-create the image, you could use a configmap to override the HTML template you want).

Could this suit to your needs ?

**Comment by emptywee** [comment]
Absolutely. Would be a good start! 👍

**Comment by fydrah** [comment]
Hi @emptywee,
The feature has been merged on 2.4.0

**Comment by fydrah** [comment]
I'm closing this issue since the feature has been merged.

Do not hesitate to open a new one if you have other feature request/issues.
